AMBIGUOUS_PACKAGES = {
    'acroread-fonts-systemwide': ['custom:non-free'],
    'adobe-base-14-fonts': ['custom:non-free'],
    'adobe-source-code-pro-fonts': ['OFL'],
    'adobe-source-sans-pro-fonts': ['OFL'],
    'adobe-source-serif-pro-fonts': ['OFL'],
    'bzip2': ['custom:bzip2'],
    'db': ['custom:Sleepycat'],
    'cups-filters': ['GPL', 'GPL2', 'GPL3-only', 'GPL3'],
    'expat': ['MIT'],
    'flashplugin': ['custom:non-free'],
    'fontconfig': ['custom:HPND'],
    'gd': ['custom:GD'],
    'ghc': ['BSD3'],
    'ghc-libs': ['BSD3'],
    'hdf5': ['BSD3'],
    'intel-ucode': ['custom:non-free'],
    'java-openjfx': ['GPL2'],
    'jdk8-openjdk': ['GPL2'],
    'jdk-openjdk': ['GPL2'],
    'jre8-openjdk': ['GPL2'],
    'jre8-openjdk-headless': ['GPL2'],
    'jre-openjdk': ['GPL2'],
    'jre-openjdk-headless': ['GPL2'],
    'jre11-openjdk': ['GPL2'],
    'jre11-openjdk-headless': ['GPL2'],
    'l-smash': ['ISC'],
    'lib32-sqlite': ['custom:publicdomain'],
    'libaec': ['BSD2'],
    'libdrm': ['MIT'],
    'libfontenc': ['MIT'],
    'libice': ['custom:X11'],
    'libldap': ['custom:OpenLDAP'],
    'libmodplug': ['custom:publicdomain'],
    'libmng': ['ZLIB'],
    'libpciaccess': ['MIT', 'ISC', 'custom:X11'],
    'libpng': ['custom:libpng'],
    'libpng12': ['custom:libpng'],
    'libsm': ['MIT', 'custom:X11'],
    'libtiff': ['custom:libtiff'],
    'libuv': ['MIT', 'BSD2', 'BSD3', 'ISC'],
    'libvdpau': ['MIT'],
    'libwpe': ['BSD2'],
    'libx11': ['MIT', 'custom:X11', 'custom:TekHVC'],
    'libxau': ['custom:X11'],
    'libxcomposite': ['custom:libxcomposite', 'MIT'],
    'libxfixes': ['custom:HPND', 'MIT'],
    'libxft': ['custom:HPND'],
    'libxi': ['custom:X11', 'custom:HPND', 'MIT'],
    'libxinerama': ['MIT', 'custom:X11'],
    'libxv': ['custom:HPND'],
    'lsof': ['custom:lsof'],
    'mesa': ['MIT', 'custom:Khronos', 'custom:SGI'],
    'mesa-demos': ['MIT', 'custom:SGI', 'LGPL'],
    'minizip': ['ZLIB'],
    'ntp': ['custom:HPND', 'BSD2'],
    'nvidia': ['custom:non-free'],
    'nvidia-dkms': ['custom:non-free'],
    'nvidia-utils': ['custom:non-free'],
    'openjdk8-src': ['GPL2'],
    'orc': ['BSD2', 'BSD3'],
    'pepper-flash': ['custom:non-free'],
    'pigz': ['ZLIB'],
    'pixman': ['MIT'],
    'python': ['Python'],
    'python2': ['Python'],
    'python-docutils': ['custom:publicdomain', 'BSD2', 'Python', 'GPL3'],
    'python-numpy': ['BSD3'],
    'popt': ['custom:X11'],
    'qhull': ['custom:Qhull'],
    'rogue': ['BSD3'],
    'rpcbind': ['BSD3'],
    'steam': ['custom:non-free'],
    'sudo': ['ISC', 'BSD3', 'BSD2', 'ZLIB'],
    'tcl': ['custom:tcl'],
    'ttf-bitstream-vera': ['custom:bitstream-vera'],
    'ttf-dejavu': ['custom:publicdomain', 'custom:bitstream-vera'],
    'unrar': ['custom:non-free'],
    'vulkan-icd-loader': ['Apache'],
    'w3m': ['custom:w3m'],
    'webrtc-audio-processing': ['BSD3'],
    'xorg-server-xwayland': ['MIT'],
    'xorg-x11perf': ['custom:HPND'],
    'xorg-xhost': ['MIT', 'custom:X11'],
    'xorg-xinput': ['MIT'],
    'xorg-xkbevd': ['custom:HPND'],
    'xorg-xkbutils': ['custom:HPND', 'custom:X11-DEC', 'MIT'],
    'zip': ['custom:Info-ZIP'],
    'zlib': ['ZLIB'],
    'zoom': ['custom:non-free'], # AUR
}

class Package(object):
    def __init__(self, name, licenses):
        self.name = name
        self.licenses = licenses

class UnambiguousDb(object):
    def __init__(self, db):
        self.packages = []

        for pkg in db.search(""):
            if pkg.name in AMBIGUOUS_PACKAGES:
                self.packages.append(Package(pkg.name, AMBIGUOUS_PACKAGES[pkg.name]))
            elif pkg.name.startswith("lib32") and pkg.name[6:] in AMBIGUOUS_PACKAGES:
                self.packages.append(Package(pkg.name, AMBIGUOUS_PACKAGES[pkg.name[6:]]))
            else:
                self.packages.append(Package(pkg.name, pkg.licenses))
