AMBIGUOUS_PACKAGES = {
    'acroread-fonts-systemwide': ['non-free'],
    'adobe-base-14-fonts': ['non-free'],
    'adobe-source-code-pro-fonts': ['OFL'],
    'adobe-source-sans-pro-fonts': ['OFL'],
    'adobe-source-serif-pro-fonts': ['OFL'],
    'amd-ucode': ['non-free'],
    'boost': ['Boost'],
    'boost-libs': ['Boost'],
    'broadcom-wl': ['non-free'],
    'bsd-games': ['BSD'],
    'bzip2': ['bzip2'],
    'cmake': ['BSD'],
    'cups-filters': ['GPL', 'GPL2', 'GPL3-only', 'GPL3'],
    'db': ['Sleepycat'],
    'discord': ['non-free'],
    'expat': ['MIT'],
    'file': ['BSD'],
    'flashplugin': ['non-free'],
    'foldingathome': ['non-free'],
    'fontconfig': ['HPND'],
    'gd': ['GD'],
    'ghc': ['BSD3'],
    'ghc-libs': ['BSD3'],
    'hdf5': ['BSD3'],
    'imagemagick': ['ImageMagick', 'Public Domain', 'MIT'],
    'intel-ucode': ['non-free'],
    'ipw2100-fw': ['non-free'],
    'ipw2200-fw': ['non-free'],
    'java-openjfx': ['GPL2'],
    'jdk11-openjdk': ['GPL2'],
    'jdk8-openjdk': ['GPL2'],
    'jdk': ['non-free'],
    'jdk-openjdk': ['GPL2'],
    'jre11-openjdk': ['GPL2'],
    'jre11-openjdk-headless': ['GPL2'],
    'jre8-openjdk': ['GPL2'],
    'jre8-openjdk-headless': ['GPL2'],
    'jre': ['non-free'],
    'jre-openjdk': ['GPL2'],
    'jre-openjdk-headless': ['GPL2'],
    'l-smash': ['ISC'],
    'lapack': ['BSD'],
    'lib32-sqlite': ['publicdomain'],
    'libaec': ['BSD2'],
    'libbsd': ['BSD', 'Expat', 'Public Domain', 'Beerware'],
    'libdrm': ['MIT'],
    'libfontenc': ['MIT'],
    'libice': ['X11'],
    'libldap': ['OpenLDAP'],
    'libmagick6': ['ImageMagick', 'Public Domain', 'MIT'],
    'libmng': ['ZLIB'],
    'libmodplug': ['publicdomain'],
    'libpciaccess': ['MIT', 'ISC', 'X11'],
    'libpng12': ['libpng'],
    'libpng': ['libpng'],
    'libsm': ['MIT', 'X11'],
    'libtiff': ['libtiff'],
    'libtommath': ['Public Domain'],
    'libuv': ['MIT', 'BSD2', 'BSD3', 'ISC'],
    'libva-mesa-driver': ['MIT', 'Khronos', 'SGI'],
    'libva-utils': ['MIT'],
    'libvdpau': ['MIT'],
    'libwpe': ['BSD2'],
    'libx11': ['MIT', 'X11', 'TekHVC'],
    'libxau': ['X11'],
    'libxaw': ['X11', 'HPND', 'MIT'],
    'libxcb': ['X11'],
    'libxcomposite': ['libxcomposite', 'MIT'],
    'libxcursor': ['HPND'],
    'libxdamage': ['HPND'],
    'libxdmcp': ['X11'],
    'libxext': ['X11', 'HPND', 'MIT'],
    'libxfixes': ['HPND', 'MIT'],
    'libxfont2': ['MIT', 'HPND', 'BSD2', 'X11'],
    'libxft': ['HPND'],
    'libxinerama': ['MIT', 'X11'],
    'libxi': ['X11', 'HPND', 'MIT'],
    'libxkbcommon': ['MIT', 'HPND', 'X11'],
    'libxkbcommon-x11': ['MIT', 'HPND', 'X11'],
    'libxkbfile': ['HPND', 'X11'],
    'libxmu': ['X11'],
    'libxpm': ['X11'],
    'libxpresent': ['MIT', 'HPND'],
    'libxrandr': ['HPND'],
    'libxrender': ['HPND'],
    'libxres': ['X11'],
    'libxslt': ['X11'],
    'libxss': ['X11'],
    'libxt': ['MIT', 'HPND', 'X11'],
    'libxtst': ['MIT', 'HPND', 'X11'],
    'libxv': ['HPND'],
    'libxxf86vm': ['X11'],
    'lolcat': ['BSD3'],
    'l-smash': ['ISC'],
    'lsof': ['lsof'],
    'mesa-demos': ['MIT', 'SGI', 'LGPL'],
    'mesa': ['MIT', 'Khronos', 'SGI'],
    'mesa-vdpau': ['MIT', 'Khronos', 'SGI'],
    'minizip': ['ZLIB'],
    'mobile-broadband-provider-info': ['Public Domain'],
    'ntp': ['HPND', 'BSD2'],
    'nvidia-cg-toolkit': ['non-free'],
    'nvidia-dkms': ['non-free'],
    'nvidia': ['non-free'],
    'nvidia-utils': ['non-free'],
    'openjdk8-src': ['GPL2'],
    'orc': ['BSD2', 'BSD3'],
    'pepper-flash': ['non-free'],
    'perl-rename': ['GPL', 'PerlArtistic'],
    'pigz': ['ZLIB'],
    'pixman': ['MIT'],
    'png++': ['BSD3'],
    'popt': ['X11'],
    'python2': ['Python'],
    'python-docutils': ['publicdomain', 'BSD2', 'Python', 'GPL3'],
    'python-magic': ['BSD2'],
    'python-numpy': ['BSD3'],
    'python': ['Python'],
    'qhull': ['Qhull'],
    'rogue': ['BSD3'],
    'rpcbind': ['BSD3'],
    'sdl_image': ['zlib'],
    'sound-theme-freedesktop': ['CC-BY-SA', 'GPL2', 'Creative Commons Attribution 3.0 Unported', 'GPL'],
    'spirv-tools': ['Apache-2.0'],
    'steam': ['non-free'],
    'sudo': ['ISC', 'BSD3', 'BSD2', 'ZLIB'],
    'tcl': ['tcl'],
    'ttf-bitstream-vera': ['bitstream-vera'],
    'ttf-dejavu': ['publicdomain', 'bitstream-vera'],
    'unrar': ['non-free'],
    'unzip': ['Info-ZIP'],
    'vdpauinfo': ['MIT'],
    'vulkan-icd-loader': ['Apache'],
    'vulkan-mesa-layers': ['MIT', 'Khronos', 'SGI'],
    'vulkan-radeon': ['MIT', 'Khronos', 'SGI'],
    'vulkan-tools': ['Apache-2.0'],
    'w3m': ['w3m'],
    'webkit2gtk': ['BSD', 'MIT', 'GPL2', 'GPL3', 'LGPL2', 'LGPL2.1', 'Unicode-DFS'],
    'webrtc-audio-processing': ['BSD3'],
    'xcb-proto': ['X11'],
    'xcb-util-image': ['X11'],
    'xcb-util-keysyms': ['HPND', 'X11'],
    'xcb-util-renderutil': ['HPND', 'X11'],
    'xcb-util-wm': ['HPND', 'X11'],
    'xcb-util': ['X11'],
    'xf86-input-libinput': ['HPND'],
    'xf86-video-amdgpu': ['X11', 'MIT', 'HPND'],
    'xfce4-wavelan-plugin': ['BSD2'],
    'xfce4-xkb-plugin': ['BSD2'],
    'xkeyboard-config': ['MIT', 'HPND', 'X11', 'MIT-style'],
    'xorg-bdftopcf': ['X11'],
    'xorg-fonts-encodings': ['Public Domain'],
    'xorg-font-util': ['UCD', 'MIT', 'BSD2'],
    'xorg-iceauth': ['X11'],
    'xorg-mkfontscale': ['MIT', 'HPND', 'X11'],
    'xorgproto': ['MIT', 'HPND', 'X11'],
    'xorg-server': ['BSD', 'MIT', 'HPND', 'X11'],
    'xorg-server-common': ['BSD', 'MIT', 'HPND', 'X11'],
    'xorg-setxkbmap': ['HPND'],
    'xorg-x11perf': ['HPND'],
    'xorg-xauth': ['X11'],
    'xorg-xdpyinfo': ['X11'],
    'xorg-xev': ['X11'],
    'xorg-xeyes': ['X11'],
    'xorg-xfontsel': ['HPND', 'X11'],
    'xorg-xhost': ['MIT', 'X11'],
    'xorg-xinit': ['X11'],
    'xorg-xinput': ['MIT'],
    'xorg-xkbcomp': ['HPND', 'X11'],
    'xorg-xkbevd': ['HPND'],
    'xorg-xkbutils': ['HPND', 'X11-DEC', 'MIT'],
    'xorg-xmessage': ['X11'],
    'xorg-xmodmap': ['MIT', 'X11'],
    'xorg-xprop': ['HPND', 'X11'],
    'xorg-xrandr': ['HPND'],
    'xorg-xrdb': ['X11'],
    'xorg-xset': ['X11'],
    'xorg-xwayland': ['MIT'],
    'youtube-dl': ['Unlicense'],
    'zathura-cb': ['zlib'],
    'zathura-djvu': ['zlib'],
    'zathura-pdf-mupdf': ['zlib'],
    'zathura-pdf-poppler': ['zlib'],
    'zathura-ps': ['zlib'],
    'zathura': ['zlib'],
    'zip': ['Info-ZIP'],
    'zlib': ['ZLIB'],
    'zoom': ['non-free'], # AUR
    'zsh': ['MIT-style', 'GPL'],
}

class Package(object):
    def __init__(self, name, licenses):
        self.name = name
        self.licenses = licenses

class UnambiguousDb(object):
    def __init__(self, db):
        self.packages = []

        for pkg in db.search(""):
            if pkg.name in AMBIGUOUS_PACKAGES:
                self.packages.append(Package(pkg.name, AMBIGUOUS_PACKAGES[pkg.name]))
            elif pkg.name.startswith("lib32") and pkg.name[6:] in AMBIGUOUS_PACKAGES:
                self.packages.append(Package(pkg.name, AMBIGUOUS_PACKAGES[pkg.name[6:]]))
            else:
                self.packages.append(Package(pkg.name, pkg.licenses))
